apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: neo4j
    component: replica
  name: neo4j-replica
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
        component: replica
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          export NEO4J_dbms_connectors_default__advertised__address=$(hostname -f)
          export NEO4J_causal__clustering_transaction__advertised__address=$(hostname -f):6000
          exec /docker-entrypoint.sh "neo4j"
        env:
        - name: NEO4J_dbms_mode
          value: READ_REPLICA
        - name: NEO4J_dbms_security_auth__enabled
          value: "false"
        - name: NEO4J_causal__clustering_discovery__type
          value: DNS

        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name: NEO4J_causal__clustering_initial__discovery__members
          value: neo4j.wow.svc.cluster.local:5000

        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"

        image: neo4j:3.4.5-enterprise
        imagePullPolicy: IfNotPresent
        name: neo4j
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        - containerPort: 6000
          name: tx
        securityContext:
          privileged: true
