apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
    component: core
  name: neo4j
spec:
  clusterIP: None
  ports:
  - name: browser
    port: 7474
    targetPort: 7474
  - name: backup
    port: 6362
    targetPort: 6362
  selector:
    app: neo4j
    component: core
